[project]
name = "eventfrog-buyer"
version = "0.1.0"
description = "Automated ticket purchasing script for Chilbi Gersau - Partyboot 2025"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "selenium>=4.15.0",
    "python-dotenv>=1.0.0",
]
